runtime: java
env: flex

handlers:
- url: /.*
  script: this field is required but ignored

network:
  forwarded_posts:
    - 80:8080

env_variables:
    API_KEY: ffe12248d8b584f9fd2af1458c6afeb23a604237
manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
